export interface PriorityFactor { name: string; weight: number; score: (m: string, s: any, p: any) => number; reason: (m: string, s: any, p: any) => string; }
export interface PriorityScore { module: string; score: number; reasons: string[]; }
function tgs(m: string, s: any, p: any): number { const k = m === "writing" ? "writing" : m === "reading" ? "reading" : m === "listening" ? "listening" : m === "speaking" ? "speaking" : ""; if (!k) return 0; const t = p.target?.[m] ?? 0; if (t <= 0) return 0; const c = s[k]?.averageBand ?? s[k]?.averageScores?.overall ?? 0; return Math.min(100, Math.max(0, t - c) * 25); }
function tgr(m: string, _s: any, p: any): string { const t = p.target?.[m]; return t ? `target ${t}` : "no target"; }
function ers(m: string, s: any): number { const e: any[] = s[m]?.topErrors ?? []; return Math.min(100, e.reduce((a: number, x: any) => a + x.count, 0) * 8); }
function err(m: string, s: any): string { const e: any[] = s[m]?.topErrors ?? []; return `${e.reduce((a: number, x: any) => a + x.count, 0)} errors`; }
function rcs(_m: string, s: any): number { if (!s.lastSnapshot) return 50; const d = Math.round((Date.now() - new Date(s.lastSnapshot).getTime()) / 86400000); return Math.max(0, 100 - d * 5); }
function rcr(_m: string, s: any): string { if (!s.lastSnapshot) return "no snapshot"; return `${Math.round((Date.now() - new Date(s.lastSnapshot).getTime()) / 86400000)}d ago`; }
function eus(_m: string, _s: any, p: any): number { if (!p.examDate) return 20; const ms = new Date(p.examDate).getTime(); if (isNaN(ms)) return 20; const d = Math.max(0, Math.ceil((ms - Date.now()) / 86400000)); return d <= 7 ? 100 : d <= 30 ? 80 : d <= 60 ? 50 : d <= 90 ? 30 : 10; }
function eur(_m: string, _s: any, p: any): string { if (!p.examDate) return "no exam date"; return `${Math.max(0, Math.ceil((new Date(p.examDate).getTime() - Date.now()) / 86400000))}d left`; }
function sds(m: string, s: any): number { if (m !== "vocab") return 0; const r = s.vocab?.wordsReviewed ?? 0; if (r === 0) return 30; return Math.min(100, Math.max(0, (1 - (s.vocab?.retentionRate ?? 0)) * 100)); }
function sdr(m: string, s: any): string { if (m !== "vocab") return "n/a"; return `${s.vocab?.wordsReviewed ?? 0} words`; }
const F = [{name:"target-gap",w:.35,s:tgs,r:tgr},{name:"error-rate",w:.25,s:ers,r:err},{name:"recency",w:.15,s:rcs,r:rcr},{name:"exam-urgency",w:.15,s:eus,r:eur},{name:"srs-due",w:.10,s:sds,r:sdr}];
export function computePriority(module: string, stats: any, profile: any): PriorityScore { let t = 0; const rs: string[] = []; for (const f of F) { const raw = f.s(module, stats, profile); const s = raw * f.w; t += s; rs.push(`${f.name}: ${f.r(module, stats, profile)} (${s.toFixed(1)})`); } return { module, score: Math.min(100, Math.max(0, Math.round(t))), reasons: rs }; }
export function getAllScores(modules: string[], stats: any, profile: any): PriorityScore[] { return modules.map(m => computePriority(m, stats, profile)).sort((a, b) => b.score - a.score); }
